version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - restore_cache:
          keys:
          - dependencies
      - run:
          name: install dependencies
          command: |
            bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: dependencies
      - run:
          name: test
          command: |
            rspec spec/spec_job.rb
            rspec spec/spec_agent.rb
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
